# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walmart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=500)),
                ('pub_time', models.DateTimeField(default=datetime.datetime(2016, 5, 7, 0, 11, 29, 873898))),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 0, 11, 29, 873501)),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walmart.User'),
        ),
    ]
