# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walmart', '0002_auto_20160507_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 20, 33, 44, 94061)),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 20, 33, 44, 93668)),
        ),
    ]
